Repository prgrms-be-devcourse/NBE3-4-2-Team03, pull requests merged in 2025-02, with the labels that each got.

#18 test : ci 테스트 테스트
  .github/workflows/main.yml
  .idea/.gitignore
  .idea/NBE3-4-2-Team03.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLibraryMappings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/build.gradle
  backend/src/main/java/com/programmers/pcquotation/PcquotationApplication.java
  backend/src/main/java/com/programmers/pcquotation/estimaterequest/controller/EstimateController.java
  backend/src/main/java/com/programmers/pcquotation/estimaterequest/entity/EstimateRequest.java
  backend/src/main/java/com/programmers/pcquotation/estimaterequest/entity/EstimateRequestDto.java
  backend/src/main/java/com/programmers/pcquotation/estimaterequest/repository/EstimateRequestRepository.java
  backend/src/main/java/com/programmers/pcquotation/estimaterequest/service/EstimateService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/test/java/com/programmers/pcquotation/PcquotationApplicationTests.java
  backend/src/test/java/com/programmers/pcquotation/estimaterequest/service/EstimateServiceTest.java
Labels: test

#26 #11 feat - 구매자 회원가입 기능 구현
  .gitignore
  .idea/.name
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/modules/pcquotation.main.iml
  backend/build.gradle
  backend/src/main/java/com/programmers/pcquotation/PcquotationApplication.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/controller/AuthController.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/dto/ErrorResponse.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/dto/SignupRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/dto/SignupResponse.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/entity/Customer.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/exception/CustomerAlreadyExistException.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/exception/CustomerExceptionHandler.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/exception/PasswordMismatchException.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/repository/CustomerRepository.java
  backend/src/main/java/com/programmers/pcquotation/domain/customers/service/AuthService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/programmers/pcquotation/customers/controller/CustomerAuthControllerTest.java
Labels: feature, test

#46 Feature/#44 견적 요청 예외 처리
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/EstimateComment.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/controller/EstimateRequestController.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/EstimateRequestDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/RsData.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/entity/EstimateRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/exception/EstimateRequestExceptionHandler.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/exception/NullEntityException.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/exception/ServerException.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/service/EstimateRequestService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/programmers/pcquotation/domain/estimaterequest/controller/EstimateRequestControllerTest.java
  backend/src/test/java/com/programmers/pcquotation/estimaterequest/service/EstimateRequestServiceTest.java
Labels: feature, refactor, test

#59 #58 feat -타임스크립트 자바 스크립트로 변경
  frontend/src/app/estimateRequest/components/form.js
  frontend/src/app/estimateRequest/request/page.js
  frontend/src/app/estimateRequest/service/service.js
Labels: feature, fix

#86 #34 feat - 구매자 및 판매자 로그인/회원가입 화면 구현
  .gitignore
  backend/src/main/java/com/programmers/pcquotation/domain/member/service/AuthService.java
  backend/src/main/java/com/programmers/pcquotation/domain/seller/controller/SellerController.java
  backend/src/main/java/com/programmers/pcquotation/domain/seller/dto/SellerSignupRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/seller/entitiy/Seller.java
  backend/src/main/java/com/programmers/pcquotation/domain/seller/repository/SellerRepository.java
  backend/src/main/java/com/programmers/pcquotation/domain/seller/service/SellerService.java
  backend/src/main/java/com/programmers/pcquotation/global/security/SecurityConfig.java
  backend/src/test/java/com/programmers/pcquotation/member/controller/AuthControllerTest.java
  backend/src/test/java/com/programmers/pcquotation/sellers/controller/PcquotationApplicationTests.java
  frontend/src/app/main/components/login-signup-view.js
  frontend/src/app/page.js
  frontend/src/app/signup/customer/page.js
  frontend/src/app/signup/seller/page.js
Labels: feature

#115 #108 fix - 서버를 시작할 때마다 데이터가 새로 생성되지 않도록 db.sql 수정
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/service/EstimateService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
Labels: fix

#119 #116 fix - 견적 요청 및 견적 생성 시간을 가독성 있게 표시
  frontend/src/app/customers/info/page.js
  frontend/src/app/sellers/info/page.js
Labels: fix

#134 #120 feat-프론트 수정, 삭제 기능 구현
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/exception/DeliveryExceptionHandler.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/RsData.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/entity/EstimateRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/exception/EstimateRequestExceptionHandler.java
  backend/src/test/java/com/programmers/pcquotation/domain/delivery/controller/DeliveryControllerTest.java
  frontend/src/app/customers/info/page.js
  frontend/src/app/estimateRequest/service/service.js
Labels: feature, fix
